POST http://localhost:3000/api/login  HTTP/1.1
Content-type: application/json

  {
   "email": "kieran.noel@icloud.com",
   "password": "123"
  }

###

POST http://localhost:3000/api/refresh HTTP/1.1
Content-type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJJZCI6ImlkMTIzIiwiZW1haWwiOiJraWVyYW4ubm9lbEBpY2xvdWQuY29tIiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTczMjc4ODQ5OSwiZXhwIjoxNzMzMzkzMjk5fQ.ripGtz4lcp7SznB7hximKjNzKc_dM1fKGzQY3Hmqge8

###