GET http://localhost:3000/api/customers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJJZCI6ImlkMTIzIiwiZW1haWwiOiJraWVyYW4ubm9lbEBpY2xvdWQuY29tIiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTczMjg4Mzk4NiwiZXhwIjoxNzMyODgzOTg3fQ.d62vDcJwKNpyXhlKfdE_87zf1bJcQ2Nsd_YzMAFmALA
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJJZCI6ImlkMTIzIiwiZW1haWwiOiJraWVyYW4ubm9lbEBpY2xvdWQuY29tIiwiaXNBZG1pbiI6dHJ1ZX0sImp0aSI6IjI1ZjE1OGRmLTA5MWQtNGZiNS1iYTU2LTE0Y2IxNzYzMGFiMSIsImlhdCI6MTczMjg4Mzk4NiwiZXhwIjoxNzMzNDg4Nzg2fQ.PMMs9ekILahHUmhhTMam5yNxn16UMO893x8H_pKPieI
### 

GET http://localhost:3000/api/fillCustomers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
###


GET http://localhost:3000/api/customers/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
### 

DELETE http://localhost:3000/api/customers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Content-Type: application/json 

{  
    "id": "0"
}

###

POST http://localhost:3000/api/customers HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Content-type: application/json

  {
    "id": "3",
    "firstName": "Kieran",
    "lastName": "Mai",
    "birthDate": "2024-10-16T22:00:00.000Z",
    "street": "",
    "city": "Berlin",
    "postalCode": "12161",
    "email": "kieran.noel@icloud.com",
    "houseNumber": ""
  }

###

PUT http://localhost:3000/api/customers HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Content-type: application/json

  {
    "id": "0",
    "firstName": "Kieran",
    "lastName": "Mai",
    "birthDate": "2024-10-16T22:00:00.000Z",
    "street": "",
    "city": "Berlin",
    "postalCode": "12161",
    "email": "kieran.noel@icloud.com",
    "houseNumber": ""
  }

###

GET http://localhost:3000/api/assets/img/logos/:customerId/:filename HTTP/1.1

###
