GET http://localhost:3000/api/customers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
### 

GET http://localhost:3000/api/fillCustomers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
###


GET http://localhost:3000/api/customers/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
### 

DELETE http://localhost:3000/api/customers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Content-Type: application/json 

{  
    "id": "0"
}

###

POST http://localhost:3000/api/customers HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Content-type: application/json

  {
    "id": "3",
    "firstName": "Kieran",
    "lastName": "Mai",
    "birthDate": "2024-10-16T22:00:00.000Z",
    "street": "",
    "city": "Berlin",
    "postalCode": "12161",
    "email": "kieran.noel@icloud.com",
    "houseNumber": ""
  }

###

PUT http://localhost:3000/api/customers HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Content-type: application/json

  {
    "id": "0",
    "firstName": "Kieran",
    "lastName": "Mai",
    "birthDate": "2024-10-16T22:00:00.000Z",
    "street": "",
    "city": "Berlin",
    "postalCode": "12161",
    "email": "kieran.noel@icloud.com",
    "houseNumber": ""
  }

###
