POST http://localhost:3000/api/testCookie
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJJZCI6ImlkMTIzIiwiZW1haWwiOiJraWVyYW4ubm9lbEBpY2xvdWQuY29tIiwiaXNBZG1pbiI6dHJ1ZX0sImp0aSI6IjI1ZjE1OGRmLTA5MWQtNGZiNS1iYTU2LTE0Y2IxNzYzMGFiMSIsImlhdCI6MTczMjg4Mzk4NiwiZXhwIjoxNzMzNDg4Nzg2fQ.PMMs9ekILahHUmhhTMam5yNxn16UMO893x8H_pKPieI
