
GET http://localhost:3000/api/fillUsers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJJZCI6ImlkMTIzIiwiZW1haWwiOiJraWVyYW4ubm9lbEBpY2xvdWQuY29tIiwiaXNBZG1pbiI6dHJ1ZX0sImp0aSI6IjI1ZjE1OGRmLTA5MWQtNGZiNS1iYTU2LTE0Y2IxNzYzMGFiMSIsImlhdCI6MTczMjg4Mzk4NiwiZXhwIjoxNzMzNDg4Nzg2fQ.PMMs9ekILahHUmhhTMam5yNxn16UMO893x8H_pKPieI

###

GET http://localhost:3000/api/testRoute
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpZDEyMyIsImVtYWlsIjoia2llcmFuLm5vZWxAaWNsb3VkLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczMjU0MDQyMH0.a2Opmz4BZEqA8_X_lg1OIlXOtoGukqe_hQ9Qnp5Srv8
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJJZCI6ImlkMTIzIiwiZW1haWwiOiJraWVyYW4ubm9lbEBpY2xvdWQuY29tIiwiaXNBZG1pbiI6dHJ1ZX0sImp0aSI6IjI1ZjE1OGRmLTA5MWQtNGZiNS1iYTU2LTE0Y2IxNzYzMGFiMSIsImlhdCI6MTczMjg4Mzk4NiwiZXhwIjoxNzMzNDg4Nzg2fQ.PMMs9ekILahHUmhhTMam5yNxn16UMO893x8H_pKPieI

###