GET http://localhost:3000/api/users

### 

GET http://localhost:3000/api/users/1

### 

DELETE http://localhost:3000/api/users
Content-Type: application/json 

{  
    "id": "0"
}

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

  {
    "id": "3",
    "firstName": "Kieran",
    "lastName": "Mai",
    "birthDate": "2024-10-16T22:00:00.000Z",
    "street": "",
    "city": "Berlin",
    "postalCode": "12161",
    "email": "kieran.noel@icloud.com",
    "houseNumber": ""
  }

###

PUT http://localhost:3000/api/users HTTP/1.1
content-type: application/json

  {
    "id": "0",
    "firstName": "Kieran",
    "lastName": "Mai",
    "birthDate": "2024-10-16T22:00:00.000Z",
    "street": "",
    "city": "Berlin",
    "postalCode": "12161",
    "email": "kieran.noel@icloud.com",
    "houseNumber": ""
  }

###